# Generated by Django 4.0.2 on 2022-02-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
