# Generated by Django 4.0.2 on 2022-03-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_statistics', 'View extra data')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
